'use client'
// import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { NextUIProvider } from "@nextui-org/react";
// import Nav from "./Components/Shared/Navbar";
import AuthProvider from "@/services/AuthProvider";
import { Toaster } from "react-hot-toast";
import Footer from "./Components/Shared/Footer";
import Nav2 from "./Components/Shared/Navbar2";
import BottomNavbar from "./Components/Shared/BottomNavbar";
import { ReactQueryDevtools } from '@tanstack/react-query-devtools'
import {
  QueryClient,
  QueryClientProvider,
} from '@tanstack/react-query';
const queryClient = new QueryClient()
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata: Metadata = {
//   title: "Electro-hub- Best Gadget Product",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background`}
      >
        <QueryClientProvider client={queryClient}>
          <NextUIProvider>
            <AuthProvider>
              <Nav2 />
              <main className=" bg-background">
                <div className="min-h-[calc(100vh-145px)] md:max-w-7xl mx-auto">
                  {children}
                </div>
              </main>
              <BottomNavbar />
              <Footer />
            </AuthProvider>
            <Toaster position="top-center" />
          </NextUIProvider>
          <ReactQueryDevtools initialIsOpen={false} />
        </QueryClientProvider>
      </body>
    </html>
  );
}
